name: tests

on: [push]

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  kustomize:
    runs-on: arc-action-kubectl
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 'configMapGenerator:
              - name: example
                literals:
                  - FOO=Bar' > kustomization.yaml
      - uses: ./
        with:
          args: kustomize
  deploy_test:
    runs-on: arc-action-kubectl
    steps:
      - uses: actions/checkout@v4
      - name: create resources
        shell: bash
        run: |
          cat <<EOF > test-resources.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-deployment
            labels:
              app: test
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: test
            template:
              metadata:
                labels:
                  app: test
              spec:
                containers:
                - name: nginx
                  image: "nginx:latest"
          EOF
      - name: apply resources
        uses: ./
        with:
          args: apply -f test-resources.yaml
      - name: Get Pod Names
        uses: ./
        with:
          args: get pods -l app=test -o jsonpath='{.items[*].metadata.name}'
          output_variable: POD_NAMES
      - name: Get Deployments
        uses: ./
        with:
          args: get deployments
          output_variable: DEPLOYMENTS
      - name: Check Output
        run: |
          error=0
          if [ -z "$DEPLOYMENTS" ]; then
            echo "ERROR: DEPLOYMENTS is empty"
            error=1
          else
            echo "DEPLOYMENTS: $DEPLOYMENTS"
          fi
          if [ -z "$POD_NAMES" ]; then
            echo "ERROR: POD_NAMES is empty"
            error=1
          else
            echo "POD_NAMES: $POD_NAMES"
          fi
          if [ "$error" -eq 1 ]; then
            exit 1
          fi
      - name: Delete Resources
        uses: ./
        with:
          args: delete -f test-resources.yaml
