name: SDK version upgrade

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: arc-action-kubectl
    steps:
      - name: Checkout repo
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"
          echo "[INFO] Cloning repository at $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .

      - name: Check if new version exist
        id: check
        run: |
          SDK_VERSION=$(curl --silent "https://api.github.com/repos/kubernetes/kubernetes/releases" | jq '.[] | select(.prerelease==false) | .tag_name' | sort -V -r | head -n 1 | tr -d '"')
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | tac | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          DOCKER_VERSION=$(cat $GITHUB_WORKSPACE/Dockerfile | grep "ARG KUBE_VERSION=" | sed -E 's/ARG KUBE_VERSION=//' | tr -d '"')
          
          echo "Provider tag: ${SDK_VERSION}"
          echo "Current tag: ${LATEST_VERSION}"
          echo "Docker tag: ${DOCKER_VERSION}"
          
          if [ "$SDK_VERSION" != "$LATEST_VERSION" ]; then
            if [ "$LATEST_VERSION" = "`echo -e "$SDK_VERSION\n$LATEST_VERSION" | sort -V | head -n1`" ]; then
              if [ "$DOCKER_VERSION" == "$LATEST_VERSION" ]; then
                echo "New version detected: $SDK_VERSION. Latest in this repo: $LATEST_VERSION. Updating..."
                echo "newest=yes" >> $GITHUB_ENV
                echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
                echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
              else
                echo "::error::Tag version in Dockerfile ($DOCKER_VERSION) is not the same as the latest release ($LATEST_VERSION)."
                exit 1
              fi
            else
              echo "newest=no" >> $GITHUB_ENV
            fi
          else
            echo "newest=no" >> $GITHUB_ENV
          fi

      - name: Check if version tag is semver and if docker hub has it
        id: test
        if: env.newest == 'yes'
        run: |
          if [[ $SDK_VERSION =~ ^v[0-9]+(\.[0-9]+){2,3}$ ]]; then
            echo "$SDK_VERSION it's semver"
          else
            echo "::error::$SDK_VERSION it's not semver!"
            exit 1
          fi
          echo "Checking if release with $SDK_VERSION tag is available"
          status_code=$(curl --silent -I https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl | grep -E "^HTTP" | awk -F " " '{print $2}')
          echo "Docker hub respond with $status_code"
          if [ "$status_code" == "200" ] ; then
            echo "exist=yes" >> $GITHUB_ENV
            echo "Newest version available"
          else
            echo "exist=no" >> $GITHUB_ENV
            echo "Docker hub returns $status_code"
          fi

      - name: Modify Dockerfile
        id: modify
        if: success() && env.newest == 'yes' && env.exist == 'yes'
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"
          git config --global user.name "jakecabrera"
          git config --global user.email "jakestengercabrera@gmail.com"
          git checkout main
          FROM_LINE="ARG KUBE_VERSION=\"$LATEST_VERSION\""
          TO_LINE="ARG KUBE_VERSION=\"$SDK_VERSION\""
          sed -i "s/${FROM_LINE}/${TO_LINE}/" $GITHUB_WORKSPACE/Dockerfile
          git add $GITHUB_WORKSPACE/Dockerfile
          git commit -m "updated kubectl to $SDK_VERSION"
          git push
          echo "tag=$SDK_VERSION" >> $GITHUB_ENV

      - name: Create new release
        if: success() && env.tag != '0'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          draft: false
          prerelease: false